### ISSUE TITLE
MiddlewareFactoryInterface should be configured in web.php

### ISSUE THREAD

**Issue by vjik** [yiisoft/request-model#13]
`Yiisoft\Middleware\Dispatcher\MiddlewareFactoryInterface` belongs to the config `web.php`, but placed to `common.php` for overwrite configuration `web.php` from `yiisoft/middleware-dispatcher` in application.

Maybe has solution for place configuration to `web.php` ?

**Comment by samdark** [comment]
Yes, it should not be in common. Does it break if just moved to web?

**Comment by vjik** [comment]
> Yes, it should not be in common. Does it break if just moved to web?

Seems this is will be work, but we can't guarantee what config plugin merge web-configuration in right order.

For the config plugin configurations `web.php` from `yiisoft/middleware-dispatcher` and `yiisoft/request-model` are on the same level.
