### ISSUE TITLE
Can't get request data

### ISSUE THREAD

**Issue by hiscaler** [yiisoft/request-model#85]
### What steps will reproduce the problem?

Upgrade latest version, and define

 i found Yiisoft\RequestModel\WrapperFactory is remove. Let's use what instead?

```
class RegisterRequest extends RequestModel implements RulesProviderInterface
{

    public function getScene(): string
    {
        $scene = (string)$this->getAttributeValue('body.scene');
        if (!$scene) {
            $scene = PassportScene::USERNAME_PASSWORD()->getValue();
        }

        return $scene;
    }
 public function getUsername(): string
    {
        return (string)$this->getAttributeValue('body.username');
    }
}
```

```
curl -X 'POST' \
  'http://127.0.0.1:8080/passport/login' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "scene": "up",
  "username": "admin",
  "password": "1"
}'
```
getUsername return empty string;

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by rustamwin** [comment]
Follow this change: https://github.com/yiisoft/demo/pull/566/files#diff-c7784cb39be5572cf093ed1501224d5893e5b3a42aa927c6e3e04989fe6f5d4a
